### ISSUE TITLE
共享书库插件库不能使用

### ISSUE THREAD

**Issue by oflg** [Zacharia2/TWPUB-Library#16]
打开twpub插件库，加载不出书。是网址改了导致的吗？

**Comment by Zacharia2** [comment]
删掉了，改成插件自己转换了。

**Comment by oflg** [comment]
okk

**Comment by Zacharia2** [comment]
我包装了更容易使用的可执行文件。大家下载后自己转换更好。且节约时间。

**Comment by Zacharia2** [comment]
EPUB2twpub，在太微组织仓库中。

**Comment by Zacharia2** [comment]
https://github.com/tiddly-gittly/Epub2twpub

这个仓库。
